blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: mailto:274720769+RealThanhNguyxn@users.noreply.github.com
    about: Please send an email if you have questions or updates regarding ownership.
